{{- if .Values.azureSecretProvider.create -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "microservice-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 4 }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ include "microservice-chart.fullname" $ }}
      type: Opaque
      data:
      {{- range $key, $objectName := .Values.azureSecretProvider.envSecrets }}
      - key: {{ $objectName }}
        objectName: {{ $objectName }}
      {{- end }}
      {{- if .Values.azureVolumeMount.create }}
      {{- range $key, $objectName := .Values.azureVolumeMount.envSecrets }}
      - key: {{ $objectName }}
        objectName: {{ $objectName }}
      {{- end }}
      {{- end }}
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: {{ .Values.azureSecretProvider.keyvault.name }}
    tenantId: {{ .Values.azureSecretProvider.keyvault.tenantId }}
    cloudName: ""
    objects: |
      array:
        {{- range $key, $objectName := .Values.azureSecretProvider.envSecrets }}
        - |
          objectName: {{ $objectName }}
          objectType: secret
          objectVersion: ""
        {{- end }}
        {{- if .Values.azureVolumeMount.create }}
        {{- range $key, $objectName := .Values.azureVolumeMount.envSecrets }}
        - |
          objectName: {{ $objectName }}
          objectType: secret
          objectVersion: ""
        {{- end }}
        {{- end }}
{{- end }}
